using DatabaseTool.Core.Interfaces;
using DatabaseTool.Core.Models;
using PgSqlParser;

namespace DatabaseTool.PostgreSQL;

public class PostgreSqlFileParser : ISqlFileParser
{
    public DatabaseDialect SupportedDialect => DatabaseDialect.PostgreSQL;

    public Task<SchemaModel> ParseAsync(string sqlContent, ExtractionOptions options, CancellationToken cancellationToken = default)
    {
        var model = new SchemaModel
        {
            Dialect = DatabaseDialect.PostgreSQL,
            SourceDescription = "PostgreSQL File"
        };

        var result = Parser.Parse(sqlContent, ParserOptions.Default);
        if (!result.IsSuccess)
            throw new InvalidOperationException($"Failed to parse SQL: {result.Error}");

        foreach (var stmt in result.Value!.Stmts)
        {
            cancellationToken.ThrowIfCancellationRequested();
            ProcessStatement(stmt.Stmt, options, model);
        }

        return Task.FromResult(model);
    }

    private static void ProcessStatement(Node node, ExtractionOptions options, SchemaModel model)
    {
        switch (node.NodeCase)
        {
            case Node.NodeOneofCase.CreateStmt when options.IncludeTables:
                ProcessCreateTable(node.CreateStmt, options, model);
                break;
            case Node.NodeOneofCase.ViewStmt when options.IncludeViews:
                ProcessCreateView(node.ViewStmt, options, model);
                break;
            case Node.NodeOneofCase.CreateFunctionStmt:
                ProcessCreateFunction(node.CreateFunctionStmt, options, model);
                break;
            case Node.NodeOneofCase.CreateTrigStmt when options.IncludeTriggers:
                ProcessCreateTrigger(node.CreateTrigStmt, model);
                break;
            case Node.NodeOneofCase.IndexStmt when options.IncludeIndexes:
                ProcessCreateIndex(node.IndexStmt, model);
                break;
            case Node.NodeOneofCase.CreateSeqStmt when options.IncludeSequences:
                ProcessCreateSequence(node.CreateSeqStmt, model);
                break;
        }
    }

    private static void ProcessCreateTable(CreateStmt createStmt, ExtractionOptions options, SchemaModel model)
    {
        var tableName = createStmt.Relation?.Relname ?? string.Empty;
        var schemaName = createStmt.Relation?.Schemaname ?? "public";

        if (!options.IsTableIncluded(tableName)) return;

        var table = new TableModel { Schema = schemaName, Name = tableName };
        var ordinal = 1;

        foreach (var elt in createStmt.TableElts)
        {
            switch (elt.NodeCase)
            {
                case Node.NodeOneofCase.ColumnDef:
                    ProcessColumnDef(elt.ColumnDef, table, ordinal++);
                    break;
                case Node.NodeOneofCase.Constraint:
                    ProcessTableConstraint(elt.Constraint, tableName, table);
                    break;
            }
        }

        model.Tables.Add(table);
    }

    private static void ProcessColumnDef(ColumnDef colDef, TableModel table, int ordinal)
    {
        var col = new ColumnModel
        {
            Name = colDef.Colname,
            DataType = GetTypeName(colDef.TypeName),
            IsNullable = !colDef.IsNotNull,
            OrdinalPosition = ordinal
        };

        // GENERATED ALWAYS / GENERATED BY DEFAULT AS IDENTITY
        if (!string.IsNullOrEmpty(colDef.Identity))
        {
            col.IsIdentity = true;
            col.IdentitySeed = 1;
            col.IdentityIncrement = 1;
        }

        // Length from type modifiers
        if (colDef.TypeName?.Typmods?.Count > 0)
        {
            var firstMod = colDef.TypeName.Typmods[0];
            if (firstMod.NodeCase == Node.NodeOneofCase.Integer)
                col.MaxLength = firstMod.Integer.Ival;
        }

        // Check if serial (maps to identity)
        var typeName = col.DataType.ToLowerInvariant();
        if (typeName is "serial" or "bigserial" or "smallserial")
        {
            col.IsIdentity = true;
            col.IdentitySeed = 1;
            col.IdentityIncrement = 1;
            col.DataType = typeName switch
            {
                "serial" => "integer",
                "bigserial" => "bigint",
                "smallserial" => "smallint",
                _ => col.DataType
            };
        }

        // Column constraints
        foreach (var cNode in colDef.Constraints)
        {
            if (cNode.NodeCase != Node.NodeOneofCase.Constraint) continue;
            var con = cNode.Constraint;

            switch (con.Contype)
            {
                case ConstrType.ConstrNotnull:
                    col.IsNullable = false;
                    break;
                case ConstrType.ConstrNull:
                    col.IsNullable = true;
                    break;
                case ConstrType.ConstrDefault:
                    col.DefaultValue = con.RawExpr?.ToString();
                    break;
                case ConstrType.ConstrPrimary:
                    table.PrimaryKey = new PrimaryKeyModel
                    {
                        Name = con.Conname ?? $"pk_{table.Name}",
                        Columns = new List<string> { col.Name }
                    };
                    break;
                case ConstrType.ConstrUnique:
                    table.UniqueConstraints.Add(new UniqueConstraintModel
                    {
                        Name = con.Conname ?? string.Empty,
                        Columns = new List<string> { col.Name }
                    });
                    break;
            }
        }

        table.Columns.Add(col);
    }

    private static void ProcessTableConstraint(Constraint con, string tableName, TableModel table)
    {
        switch (con.Contype)
        {
            case ConstrType.ConstrPrimary:
                table.PrimaryKey = new PrimaryKeyModel
                {
                    Name = con.Conname ?? $"pk_{tableName}",
                    Columns = ExtractStringList(con.Keys)
                };
                break;
            case ConstrType.ConstrUnique:
                table.UniqueConstraints.Add(new UniqueConstraintModel
                {
                    Name = con.Conname ?? string.Empty,
                    Columns = ExtractStringList(con.Keys)
                });
                break;
            case ConstrType.ConstrForeign:
                table.ForeignKeys.Add(new ForeignKeyModel
                {
                    Name = con.Conname ?? string.Empty,
                    Columns = ExtractStringList(con.FkAttrs),
                    ReferencedTable = con.Pktable?.Relname ?? string.Empty,
                    ReferencedSchema = con.Pktable?.Schemaname ?? "public",
                    ReferencedColumns = ExtractStringList(con.PkAttrs),
                    OnDelete = ParseFkAction(con.FkDelAction),
                    OnUpdate = ParseFkAction(con.FkUpdAction)
                });
                break;
            case ConstrType.ConstrCheck:
                table.CheckConstraints.Add(new CheckConstraintModel
                {
                    Name = con.Conname ?? string.Empty,
                    Expression = con.RawExpr?.ToString() ?? string.Empty
                });
                break;
        }
    }

    private static void ProcessCreateView(ViewStmt viewStmt, ExtractionOptions options, SchemaModel model)
    {
        var viewName = viewStmt.View?.Relname ?? string.Empty;
        if (!options.IsViewIncluded(viewName)) return;

        model.Views.Add(new ViewModel
        {
            Schema = viewStmt.View?.Schemaname ?? "public",
            Name = viewName,
            Definition = viewStmt.Query?.ToString() ?? string.Empty
        });
    }

    private static void ProcessCreateFunction(CreateFunctionStmt funcStmt, ExtractionOptions options, SchemaModel model)
    {
        var nameParts = funcStmt.Funcname;
        var name = nameParts?.Count > 0
            ? nameParts[nameParts.Count - 1].String?.Sval ?? string.Empty
            : string.Empty;
        var schema = nameParts?.Count > 1
            ? nameParts[0].String?.Sval ?? "public"
            : "public";

        var returnType = GetTypeName(funcStmt.ReturnType);
        var parameters = funcStmt.Parameters
            .Where(p => p.NodeCase == Node.NodeOneofCase.FunctionParameter)
            .Select(p =>
            {
                var fp = p.FunctionParameter;
                return new RoutineParameterModel
                {
                    Name = fp.Name ?? string.Empty,
                    DataType = GetTypeName(fp.ArgType),
                    Direction = fp.Mode switch
                    {
                        FunctionParameterMode.FuncParamOut => ParameterDirection.Output,
                        FunctionParameterMode.FuncParamInout => ParameterDirection.InputOutput,
                        _ => ParameterDirection.Input
                    }
                };
            })
            .ToList();

        if (funcStmt.IsProcedure)
        {
            if (!options.IsProcedureIncluded(name)) return;
            model.Procedures.Add(new ProcedureModel
            {
                Schema = schema,
                Name = name,
                Definition = funcStmt.ToString() ?? string.Empty,
                Parameters = parameters
            });
        }
        else
        {
            if (!options.IsFunctionIncluded(name)) return;
            model.Functions.Add(new FunctionModel
            {
                Schema = schema,
                Name = name,
                Definition = funcStmt.ToString() ?? string.Empty,
                ReturnType = returnType,
                Parameters = parameters
            });
        }
    }

    private static void ProcessCreateTrigger(CreateTrigStmt trigStmt, SchemaModel model)
    {
        var trigger = new TriggerModel
        {
            Name = trigStmt.Trigname ?? string.Empty,
            TableName = trigStmt.Relation?.Relname ?? string.Empty,
            TableSchema = trigStmt.Relation?.Schemaname ?? "public",
            Timing = trigStmt.Timing switch
            {
                64 => TriggerTiming.After,
                2 => TriggerTiming.Before,
                _ => TriggerTiming.InsteadOf
            },
            Definition = trigStmt.ToString() ?? string.Empty
        };

        var events = trigStmt.Events;
        if ((events & 4) != 0) trigger.Events.Add(TriggerEvent.Insert);
        if ((events & 16) != 0) trigger.Events.Add(TriggerEvent.Update);
        if ((events & 8) != 0) trigger.Events.Add(TriggerEvent.Delete);

        model.Triggers.Add(trigger);
    }

    private static void ProcessCreateIndex(IndexStmt indexStmt, SchemaModel model)
    {
        var tableName = indexStmt.Relation?.Relname ?? string.Empty;
        var table = model.Tables.FirstOrDefault(t =>
            string.Equals(t.Name, tableName, StringComparison.OrdinalIgnoreCase));

        if (table is null) return;

        var index = new IndexModel
        {
            Name = indexStmt.Idxname ?? string.Empty,
            IsUnique = indexStmt.Unique,
            Columns = indexStmt.IndexParams
                .Where(p => p.NodeCase == Node.NodeOneofCase.IndexElem)
                .Select(p => p.IndexElem.Name ?? string.Empty)
                .Where(n => n.Length > 0)
                .ToList(),
            IncludedColumns = indexStmt.IndexIncludingParams
                .Where(p => p.NodeCase == Node.NodeOneofCase.IndexElem)
                .Select(p => p.IndexElem.Name ?? string.Empty)
                .Where(n => n.Length > 0)
                .ToList(),
            FilterExpression = indexStmt.WhereClause?.NodeCase != Node.NodeOneofCase.None
                ? indexStmt.WhereClause?.ToString()
                : null
        };

        table.Indexes.Add(index);
    }

    private static void ProcessCreateSequence(CreateSeqStmt seqStmt, SchemaModel model)
    {
        model.Sequences.Add(new SequenceModel
        {
            Schema = seqStmt.Sequence?.Schemaname ?? "public",
            Name = seqStmt.Sequence?.Relname ?? string.Empty
        });
    }

    private static string GetTypeName(TypeName? typeName)
    {
        if (typeName is null) return string.Empty;
        return typeName.Names
            .Where(n => n.NodeCase == Node.NodeOneofCase.String && n.String.Sval != "pg_catalog")
            .Select(n => n.String.Sval)
            .LastOrDefault() ?? string.Empty;
    }

    private static List<string> ExtractStringList(Google.Protobuf.Collections.RepeatedField<Node> nodes) =>
        nodes
            .Where(n => n.NodeCase == Node.NodeOneofCase.String)
            .Select(n => n.String.Sval)
            .ToList();

    private static ForeignKeyAction ParseFkAction(string action) => action switch
    {
        "c" => ForeignKeyAction.Cascade,
        "n" => ForeignKeyAction.SetNull,
        "d" => ForeignKeyAction.SetDefault,
        "r" => ForeignKeyAction.Restrict,
        _ => ForeignKeyAction.NoAction
    };
}
