using System.Text;
using System.Text.RegularExpressions;
using DatabaseTool.Core.Interfaces;
using DatabaseTool.Core.Models;

namespace DatabaseTool.Core.Conversion;

public class PostgreSqlToSqlServerConverter : ISchemaConverter
{
    public ConversionDirection Direction => ConversionDirection.PostgreSQLToSqlServer;

    public Task<ConversionResult> ConvertAsync(SchemaModel source, ConversionOptions options, CancellationToken cancellationToken = default)
    {
        var sb = new StringBuilder();
        var warnings = new List<ConversionWarning>();
        var mapping = options.TypeMapping ?? TypeMappingConfig.Default;

        sb.AppendLine("-- Generated by Database Schema Tool");
        sb.AppendLine($"-- Source: {source.SourceDescription}");
        sb.AppendLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"-- Direction: PostgreSQL → SQL Server");
        sb.AppendLine();

        // Tables
        foreach (var table in source.Tables)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertTable(table, options, mapping, warnings));
        }

        // Indexes
        foreach (var table in source.Tables)
        {
            foreach (var index in table.Indexes)
            {
                cancellationToken.ThrowIfCancellationRequested();
                sb.AppendLine(ConvertIndex(index, table.Schema, table.Name));
            }
        }

        // Views
        foreach (var view in source.Views)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertView(view, options, warnings));
        }

        // Functions
        foreach (var func in source.Functions)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertRoutine(func.Name, func.Definition, "FUNCTION", warnings));
        }

        // Procedures
        foreach (var proc in source.Procedures)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertRoutine(proc.Name, proc.Definition, "PROCEDURE", warnings));
        }

        // Triggers
        foreach (var trigger in source.Triggers)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertRoutine(trigger.Name, trigger.Definition, "TRIGGER", warnings));
        }

        return Task.FromResult(new ConversionResult
        {
            Script = sb.ToString(),
            Warnings = warnings
        });
    }

    private static string ConvertTable(TableModel table, ConversionOptions options, TypeMappingConfig mapping, List<ConversionWarning> warnings)
    {
        var sb = new StringBuilder();
        var ssSchema = table.Schema == "public" ? "dbo" : table.Schema;

        if (options.IncludeDropStatements)
        {
            sb.AppendLine($"IF OBJECT_ID(N'[{ssSchema}].[{table.Name}]', 'U') IS NOT NULL DROP TABLE [{ssSchema}].[{table.Name}];");
        }

        sb.AppendLine($"CREATE TABLE [{ssSchema}].[{table.Name}] (");

        var colDefs = new List<string>();

        foreach (var col in table.Columns.OrderBy(c => c.OrdinalPosition))
        {
            colDefs.Add(ConvertColumn(col, mapping, warnings));
        }

        // PK constraint
        if (table.PrimaryKey is not null && table.PrimaryKey.Columns.Count > 0)
        {
            var pkCols = string.Join(", ", table.PrimaryKey.Columns.Select(c => $"[{c}]"));
            var clustered = table.PrimaryKey.IsClustered ? "CLUSTERED" : "NONCLUSTERED";
            colDefs.Add($"    CONSTRAINT [{table.PrimaryKey.Name}] PRIMARY KEY {clustered} ({pkCols})");
        }

        // Unique constraints
        foreach (var uq in table.UniqueConstraints)
        {
            var uqCols = string.Join(", ", uq.Columns.Select(c => $"[{c}]"));
            colDefs.Add($"    CONSTRAINT [{uq.Name}] UNIQUE ({uqCols})");
        }

        // Check constraints
        foreach (var chk in table.CheckConstraints)
        {
            var expr = ConvertExpression(chk.Expression);
            colDefs.Add($"    CONSTRAINT [{chk.Name}] CHECK ({expr})");
        }

        // Foreign keys
        foreach (var fk in table.ForeignKeys)
        {
            var fkCols = string.Join(", ", fk.Columns.Select(c => $"[{c}]"));
            var refSchema = fk.ReferencedSchema == "public" ? "dbo" : fk.ReferencedSchema;
            var refCols = string.Join(", ", fk.ReferencedColumns.Select(c => $"[{c}]"));
            var onDelete = FkActionToSql(fk.OnDelete);
            var onUpdate = FkActionToSql(fk.OnUpdate);
            colDefs.Add($"    CONSTRAINT [{fk.Name}] FOREIGN KEY ({fkCols}) REFERENCES [{refSchema}].[{fk.ReferencedTable}] ({refCols}) ON DELETE {onDelete} ON UPDATE {onUpdate}");
        }

        sb.AppendLine(string.Join($",{Environment.NewLine}", colDefs));
        sb.AppendLine(");");
        sb.AppendLine("GO");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string ConvertColumn(ColumnModel col, TypeMappingConfig mapping, List<ConversionWarning> warnings)
    {
        if (col.IsIdentity)
        {
            var seed = col.IdentitySeed ?? 1;
            var inc = col.IdentityIncrement ?? 1;
            var baseType = mapping.MapPostgreSQLToSqlServer(col.DataType);
            return $"    [{col.Name}] {baseType} IDENTITY({seed},{inc}) NOT NULL";
        }

        var ssType = MapType(col, mapping, warnings);
        var nullable = col.IsNullable ? "NULL" : "NOT NULL";
        var defaultClause = col.DefaultValue is not null
            ? $" DEFAULT {ConvertDefaultValue(col.DefaultValue)}"
            : string.Empty;

        return $"    [{col.Name}] {ssType}{defaultClause} {nullable}";
    }

    private static string MapType(ColumnModel col, TypeMappingConfig mapping, List<ConversionWarning> warnings)
    {
        var baseType = col.DataType.ToLowerInvariant();
        var mapped = mapping.MapPostgreSQLToSqlServer(baseType);

        // Apply length/precision
        if (mapped.Contains("nvarchar") || mapped.Contains("varchar") || mapped.Contains("nchar") || mapped.Contains("char"))
        {
            if (!mapped.Contains("("))
            {
                if (col.MaxLength.HasValue && col.MaxLength > 0)
                    return mapped.ToUpper() + $"({col.MaxLength})";
                return mapped.ToUpper() + "(MAX)";
            }
        }

        if (mapped.Contains("decimal") || mapped.Contains("numeric"))
        {
            if (!mapped.Contains("(") && col.Precision.HasValue)
            {
                if (col.Scale.HasValue)
                    return mapped.ToUpper() + $"({col.Precision},{col.Scale})";
                return mapped.ToUpper() + $"({col.Precision})";
            }
        }

        // Warn on unmappable types
        if (baseType is "json" or "jsonb" or "hstore" or "bytea")
        {
            warnings.Add(new ConversionWarning
            {
                ObjectName = col.Name,
                Message = $"Type '{baseType}' has no direct SQL Server equivalent. Mapped to NVARCHAR(MAX).",
                Severity = WarningSeverity.Warning
            });
        }

        return mapped.ToUpper();
    }

    private static string ConvertIndex(IndexModel index, string schema, string tableName)
    {
        var ssSchema = schema == "public" ? "dbo" : schema;
        var unique = index.IsUnique ? "UNIQUE " : string.Empty;
        var cols = string.Join(", ", index.Columns.Select(c => $"[{c}]"));

        var sb = new StringBuilder();
        sb.Append($"CREATE {unique}INDEX [{index.Name}] ON [{ssSchema}].[{tableName}] ({cols})");

        if (index.IncludedColumns.Count > 0)
        {
            var included = string.Join(", ", index.IncludedColumns.Select(c => $"[{c}]"));
            sb.Append($" INCLUDE ({included})");
        }

        if (!string.IsNullOrEmpty(index.FilterExpression))
            sb.Append($" WHERE {ConvertExpression(index.FilterExpression)}");

        sb.AppendLine(";");
        sb.AppendLine("GO");
        return sb.ToString();
    }

    private static string ConvertView(ViewModel view, ConversionOptions options, List<ConversionWarning> warnings)
    {
        var ssSchema = view.Schema == "public" ? "dbo" : view.Schema;
        var def = BestEffortConvertPostgresToTSql(view.Definition, warnings, view.Name);
        return $"CREATE OR ALTER VIEW [{ssSchema}].[{view.Name}] AS\n{def}\nGO\n";
    }

    private static string ConvertRoutine(string name, string definition, string routineType, List<ConversionWarning> warnings)
    {
        var converted = BestEffortConvertPostgresToTSql(definition, warnings, name);
        return $"-- {routineType}: {name}\n-- [REVIEW REQUIRED] PL/pgSQL → T-SQL requires manual review\n{converted}\nGO\n";
    }

    private static string BestEffortConvertPostgresToTSql(string definition, List<ConversionWarning> warnings, string objectName)
    {
        var result = definition;

        // Common function replacements
        result = Regex.Replace(result, @"\bNOW\s*\(\s*\)", "GETDATE()", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bCOALESCE\s*\(", "ISNULL(", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bLENGTH\s*\(", "LEN(", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bgen_random_uuid\s*\(\s*\)", "NEWID()", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bBOOLEAN\b", "BIT", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bTIMESTAMP\b", "DATETIME2", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bUUID\b", "UNIQUEIDENTIFIER", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bINTEGER\b", "INT", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bTEXT\b", "NVARCHAR(MAX)", RegexOptions.IgnoreCase);

        // Double-quote identifiers → square bracket
        result = Regex.Replace(result, "\"([^\"]+)\"", "[$1]");

        // LIMIT n → TOP n (basic inline select only - imperfect but common case)
        result = Regex.Replace(result, @"\bLIMIT\s+(\d+)\b", "-- LIMIT $1 (convert to TOP in SELECT)", RegexOptions.IgnoreCase);

        if (Regex.IsMatch(result, @"\bPLPGSQL\b|\$\$|\bRAISE\b|\bRETURN\s+QUERY\b|\bFOR\s+\w+\s+IN\b", RegexOptions.IgnoreCase))
        {
            result = "-- [REVIEW REQUIRED] PL/pgSQL constructs detected\n" + result;
            warnings.Add(new ConversionWarning
            {
                ObjectName = objectName,
                Message = "PL/pgSQL constructs detected that have no direct T-SQL equivalent.",
                Severity = WarningSeverity.Warning
            });
        }

        return result;
    }

    private static string ConvertExpression(string expr)
    {
        expr = Regex.Replace(expr, "\"([^\"]+)\"", "[$1]");
        expr = Regex.Replace(expr, @"\bCOALESCE\s*\(", "ISNULL(", RegexOptions.IgnoreCase);
        return expr;
    }

    private static string ConvertDefaultValue(string defaultValue)
    {
        var val = defaultValue.Trim();

        return val.ToUpperInvariant() switch
        {
            "NOW()" or "CURRENT_TIMESTAMP" => "GETDATE()",
            "GEN_RANDOM_UUID()" => "NEWID()",
            "TRUE" => "1",
            "FALSE" => "0",
            _ => val
        };
    }

    private static string FkActionToSql(ForeignKeyAction action) => action switch
    {
        ForeignKeyAction.Cascade => "CASCADE",
        ForeignKeyAction.SetNull => "SET NULL",
        ForeignKeyAction.SetDefault => "SET DEFAULT",
        ForeignKeyAction.Restrict => "NO ACTION",
        _ => "NO ACTION"
    };
}
