using System.Text;
using System.Text.RegularExpressions;
using DatabaseTool.Core.Interfaces;
using DatabaseTool.Core.Models;

namespace DatabaseTool.Core.Conversion;

public class SqlServerToPostgreSqlConverter : ISchemaConverter
{
    public ConversionDirection Direction => ConversionDirection.SqlServerToPostgreSQL;

    public Task<ConversionResult> ConvertAsync(SchemaModel source, ConversionOptions options, CancellationToken cancellationToken = default)
    {
        var sb = new StringBuilder();
        var warnings = new List<ConversionWarning>();
        var mapping = options.TypeMapping ?? TypeMappingConfig.Default;

        sb.AppendLine("-- Generated by Database Schema Tool");
        sb.AppendLine($"-- Source: {source.SourceDescription}");
        sb.AppendLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"-- Direction: SQL Server → PostgreSQL");
        sb.AppendLine();

        // Sequences first
        foreach (var seq in source.Sequences)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertSequence(seq, options));
        }

        // Tables
        foreach (var table in source.Tables)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertTable(table, options, mapping, warnings));
        }

        // Indexes (outside CREATE TABLE)
        foreach (var table in source.Tables)
        {
            foreach (var index in table.Indexes)
            {
                cancellationToken.ThrowIfCancellationRequested();
                sb.AppendLine(ConvertIndex(index, table.Name, options));
            }
        }

        // Views
        foreach (var view in source.Views)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertView(view, options, warnings));
        }

        // Functions
        foreach (var func in source.Functions)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertRoutine(func.Name, func.Definition, "FUNCTION", options, warnings));
        }

        // Procedures
        foreach (var proc in source.Procedures)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertRoutine(proc.Name, proc.Definition, "PROCEDURE", options, warnings));
        }

        // Triggers
        foreach (var trigger in source.Triggers)
        {
            cancellationToken.ThrowIfCancellationRequested();
            sb.AppendLine(ConvertRoutine(trigger.Name, trigger.Definition, "TRIGGER", options, warnings));
        }

        return Task.FromResult(new ConversionResult
        {
            Script = sb.ToString(),
            Warnings = warnings
        });
    }

    private static string ConvertTable(TableModel table, ConversionOptions options, TypeMappingConfig mapping, List<ConversionWarning> warnings)
    {
        var sb = new StringBuilder();
        var pgSchema = table.Schema == "dbo" ? options.TargetSchema : table.Schema.ToLowerInvariant();
        var pgTableName = table.Name.ToLowerInvariant();

        if (options.IncludeDropStatements)
            sb.AppendLine($"DROP TABLE IF EXISTS {pgSchema}.{pgTableName} CASCADE;");

        var createOr = options.UseIfNotExists ? "CREATE TABLE IF NOT EXISTS" : "CREATE TABLE";
        sb.AppendLine($"{createOr} {pgSchema}.{pgTableName} (");

        var colDefs = new List<string>();

        foreach (var col in table.Columns.OrderBy(c => c.OrdinalPosition))
        {
            colDefs.Add(ConvertColumn(col, mapping, warnings));
        }

        // Primary key inline
        if (table.PrimaryKey is not null && table.PrimaryKey.Columns.Count > 0)
        {
            var pkCols = string.Join(", ", table.PrimaryKey.Columns.Select(c => c.ToLowerInvariant()));
            colDefs.Add($"    CONSTRAINT {table.PrimaryKey.Name.ToLowerInvariant()} PRIMARY KEY ({pkCols})");
        }

        // Unique constraints
        foreach (var uq in table.UniqueConstraints)
        {
            var uqCols = string.Join(", ", uq.Columns.Select(c => c.ToLowerInvariant()));
            colDefs.Add($"    CONSTRAINT {uq.Name.ToLowerInvariant()} UNIQUE ({uqCols})");
        }

        // Check constraints
        foreach (var chk in table.CheckConstraints)
        {
            var expr = ConvertExpression(chk.Expression);
            colDefs.Add($"    CONSTRAINT {chk.Name.ToLowerInvariant()} CHECK ({expr})");
        }

        // Foreign keys
        foreach (var fk in table.ForeignKeys)
        {
            var fkCols = string.Join(", ", fk.Columns.Select(c => c.ToLowerInvariant()));
            var refSchema = fk.ReferencedSchema == "dbo" ? options.TargetSchema : fk.ReferencedSchema.ToLowerInvariant();
            var refCols = string.Join(", ", fk.ReferencedColumns.Select(c => c.ToLowerInvariant()));
            var onDelete = FkActionToSql(fk.OnDelete);
            var onUpdate = FkActionToSql(fk.OnUpdate);
            colDefs.Add($"    CONSTRAINT {fk.Name.ToLowerInvariant()} FOREIGN KEY ({fkCols}) REFERENCES {refSchema}.{fk.ReferencedTable.ToLowerInvariant()} ({refCols}) ON DELETE {onDelete} ON UPDATE {onUpdate}");
        }

        sb.AppendLine(string.Join($",{Environment.NewLine}", colDefs));
        sb.AppendLine(");");
        sb.AppendLine();

        return sb.ToString();
    }

    private static string ConvertColumn(ColumnModel col, TypeMappingConfig mapping, List<ConversionWarning> warnings)
    {
        var colName = col.Name.ToLowerInvariant();
        string pgType;

        if (col.IsIdentity)
        {
            pgType = "GENERATED ALWAYS AS IDENTITY";
            var baseType = mapping.MapSqlServerToPostgreSQL(col.DataType);
            return $"    {colName} {baseType} {pgType}";
        }

        pgType = MapType(col, mapping, warnings);

        var nullable = col.IsNullable ? "NULL" : "NOT NULL";
        var defaultClause = col.DefaultValue is not null
            ? $" DEFAULT {ConvertDefaultValue(col.DefaultValue)}"
            : string.Empty;

        return $"    {colName} {pgType}{defaultClause} {nullable}";
    }

    private static string MapType(ColumnModel col, TypeMappingConfig mapping, List<ConversionWarning> warnings)
    {
        var baseType = col.DataType.ToLowerInvariant();

        // Handle MAX length
        if (col.MaxLength == -1)
        {
            return baseType switch
            {
                "varchar" or "nvarchar" => "TEXT",
                "varbinary" => "BYTEA",
                _ => "TEXT"
            };
        }

        var mapped = mapping.MapSqlServerToPostgreSQL(baseType);

        // Apply length/precision
        if (mapped is "varchar" or "char" or "character varying" or "character")
        {
            if (col.MaxLength.HasValue && col.MaxLength > 0)
                return $"{mapped.ToUpper()}({col.MaxLength})";
            return mapped.ToUpper();
        }

        if (mapped is "numeric" or "decimal")
        {
            if (col.Precision.HasValue && col.Scale.HasValue)
                return $"{mapped.ToUpper()}({col.Precision},{col.Scale})";
            if (col.Precision.HasValue)
                return $"{mapped.ToUpper()}({col.Precision})";
            return mapped.ToUpper();
        }

        return mapped.ToUpper();
    }

    private static string ConvertIndex(IndexModel index, string tableName, ConversionOptions options)
    {
        var unique = index.IsUnique ? "UNIQUE " : string.Empty;
        var cols = string.Join(", ", index.Columns.Select(c => c.ToLowerInvariant()));
        var sb = new StringBuilder();

        var createOr = options.UseIfNotExists ? "CREATE " + unique + "INDEX IF NOT EXISTS" : "CREATE " + unique + "INDEX";
        sb.Append($"{createOr} {index.Name.ToLowerInvariant()} ON {tableName.ToLowerInvariant()} ({cols})");

        if (index.IncludedColumns.Count > 0)
        {
            var included = string.Join(", ", index.IncludedColumns.Select(c => c.ToLowerInvariant()));
            sb.Append($" INCLUDE ({included})");
        }

        if (!string.IsNullOrEmpty(index.FilterExpression))
            sb.Append($" WHERE {ConvertExpression(index.FilterExpression)}");

        sb.AppendLine(";");
        return sb.ToString();
    }

    private static string ConvertSequence(SequenceModel seq, ConversionOptions options)
    {
        var createOr = options.UseIfNotExists ? "CREATE SEQUENCE IF NOT EXISTS" : "CREATE SEQUENCE";
        var schema = seq.Schema == "dbo" ? options.TargetSchema : seq.Schema.ToLowerInvariant();
        return $"{createOr} {schema}.{seq.Name.ToLowerInvariant()} START {seq.StartValue} INCREMENT {seq.Increment};";
    }

    private static string ConvertView(ViewModel view, ConversionOptions options, List<ConversionWarning> warnings)
    {
        var pgSchema = view.Schema == "dbo" ? options.TargetSchema : view.Schema.ToLowerInvariant();
        var def = ConvertViewDefinition(view.Definition, options.TargetSchema, warnings, view.Name);
        var createOr = options.UseIfNotExists ? "CREATE OR REPLACE VIEW" : "CREATE VIEW";
        return $"{createOr} {pgSchema}.{view.Name.ToLowerInvariant()} AS\n{def}\n";
    }

    private static string ConvertRoutine(string name, string definition, string routineType, ConversionOptions options, List<ConversionWarning> warnings)
    {
        var converted = BestEffortConvertRoutineBody(definition, options.TargetSchema, warnings, name);
        return $"-- {routineType}: {name}\n{converted}\n";
    }

    private static string ConvertViewDefinition(string definition, string targetSchema, List<ConversionWarning> warnings, string objectName)
    {
        var result = ApplyCommonTSqlToPostgresSqlTransformations(definition, targetSchema);
        if (result.HasReviewMarkers)
        {
            warnings.Add(new ConversionWarning
            {
                ObjectName = objectName,
                Message = "View definition contains T-SQL syntax that may require manual review.",
                Severity = WarningSeverity.Warning
            });
        }
        return result.Sql;
    }

    private static string BestEffortConvertRoutineBody(string definition, string targetSchema, List<ConversionWarning> warnings, string objectName)
    {
        var result = ApplyCommonTSqlToPostgresSqlTransformations(definition, targetSchema);

        warnings.Add(new ConversionWarning
        {
            ObjectName = objectName,
            Message = "Stored procedure/function body requires manual review. T-SQL and PL/pgSQL have significant syntax differences.",
            Severity = WarningSeverity.Warning,
            OriginalCode = definition
        });

        return $"-- [REVIEW REQUIRED] The following was converted best-effort from T-SQL\n-- Manual review is required for procedure/function bodies\n{result.Sql}";
    }

    private static (string Sql, bool HasReviewMarkers) ApplyCommonTSqlToPostgresSqlTransformations(string sql, string targetSchema)
    {
        var hasReview = false;
        var result = sql;

        // Schema replacement
        result = Regex.Replace(result, @"\bdbo\.", $"{targetSchema}.", RegexOptions.IgnoreCase);

        // Common function replacements
        result = Regex.Replace(result, @"\bGETDATE\s*\(\s*\)", "NOW()", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bGETUTCDATE\s*\(\s*\)", "NOW() AT TIME ZONE 'UTC'", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bISNULL\s*\(", "COALESCE(", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bLEN\s*\(", "LENGTH(", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bCHARINDEX\s*\(([^,]+),([^)]+)\)", "POSITION($1 IN $2)", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bSUBSTRING\s*\(", "SUBSTRING(", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bNEWID\s*\(\s*\)", "gen_random_uuid()", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bCAST\s*\(([^)]+)\s+AS\s+NVARCHAR\b", "CAST($1 AS VARCHAR", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bNVARCHAR\b", "VARCHAR", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bDATETIME\b", "TIMESTAMP", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bBIT\b", "BOOLEAN", RegexOptions.IgnoreCase);
        result = Regex.Replace(result, @"\bUNIQUEIDENTIFIER\b", "UUID", RegexOptions.IgnoreCase);

        // TOP n → LIMIT n (basic cases)
        result = Regex.Replace(result, @"\bTOP\s+(\d+)\b", "LIMIT $1", RegexOptions.IgnoreCase);

        // Square bracket identifiers → double-quote
        result = Regex.Replace(result, @"\[([^\]]+)\]", "\"$1\"");

        // N'string' → 'string'
        result = Regex.Replace(result, @"\bN'", "'", RegexOptions.IgnoreCase);

        // Mark complex T-SQL patterns that need manual review
        if (Regex.IsMatch(result, @"\bCURSOR\b|\bFETCH\b|\bDECLARE\s+@|\bSET\s+@|\bBEGIN\s+TRY|\bXACT_ABORT\b", RegexOptions.IgnoreCase))
        {
            result = "-- [REVIEW REQUIRED] Complex T-SQL constructs detected below\n" + result;
            hasReview = true;
        }

        return (result, hasReview);
    }

    private static string ConvertExpression(string expr)
    {
        expr = Regex.Replace(expr, @"\[([^\]]+)\]", "\"$1\"");
        expr = Regex.Replace(expr, @"\bISNULL\s*\(", "COALESCE(", RegexOptions.IgnoreCase);
        return expr;
    }

    private static string ConvertDefaultValue(string defaultValue)
    {
        var val = defaultValue.Trim().TrimStart('(').TrimEnd(')');

        return val.ToUpperInvariant() switch
        {
            "GETDATE()" or "GETDATE" => "NOW()",
            "GETUTCDATE()" or "GETUTCDATE" => "NOW() AT TIME ZONE 'UTC'",
            "NEWID()" or "NEWID" => "gen_random_uuid()",
            "1" => "TRUE",
            "0" => "FALSE",
            _ => val
        };
    }

    private static string FkActionToSql(ForeignKeyAction action) => action switch
    {
        ForeignKeyAction.Cascade => "CASCADE",
        ForeignKeyAction.SetNull => "SET NULL",
        ForeignKeyAction.SetDefault => "SET DEFAULT",
        ForeignKeyAction.Restrict => "RESTRICT",
        _ => "NO ACTION"
    };
}
