<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DatabaseTool.Core\DatabaseTool.Core.csproj" />
    <ProjectReference Include="..\DatabaseTool.SqlServer\DatabaseTool.SqlServer.csproj" />
    <ProjectReference Include="..\DatabaseTool.PostgreSQL\DatabaseTool.PostgreSQL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
